### ISSUE TITLE
Number parsing isn't IEEE compatible

### ISSUE THREAD

**Issue by 9il** [atilaneves/unit-threaded#229] opened 2020-11-25 12:54 UTC
Likely it is a [Phobos issue](https://issues.dlang.org/show_bug.cgi?id=20967).

**Comment by atilaneves** [comment] 2020-11-25 14:14
I don't know what this issue means. What's the reproducible case? What happens and what did you expect to happen?

I don't even remember anywhere where unit-threaded parses numbers.

**Comment by 9il** [comment] 2020-11-25 15:02
https://github.com/atilaneves/unit-threaded/blob/98dc4c99598e2b6c885a7cc82db35527af0d786d/subpackages/assertions/source/unit_threaded/assertions.d#L929

@John-Colvin  asked me to add this

**Comment by atilaneves** [comment] 2020-11-25 15:50
So it's a problem with parsing JSON that's done by a function in Phobos? That isn't a unit-threaded bug. Nor is it "number parsing".

**Comment by John-Colvin** [comment] 2020-11-26 11:17
The problem is that `unit-threaded` says "I will compare json X to json Y" and it does it subtly wrong. The fact that the implementation uses phobos and that is the underlying cause doesn't change the existence of the flaw here.

It's not a big problem, but I believe it's a legit unit-threaded bug.

See your mentions on symmetry git for more context.

**Comment by atilaneves** [comment] 2020-11-26 11:43
I understand the argument about users not needing to care about implementation details. But:

1. Fixing it means either changing the implementation or fixing Phobos
2. Changing the implementation means adding a dependency to parse JSON instead
3. The function's implementation is basically trivial and users can write their own to compare JSON instead

People really should write more of their own custom assertions using the building blocks here. Given that there's an easy workaround and that adding a dependency to fix a niche use case of JSON parsing is overkill, I'm going to close this.

**Closed by atilaneves** 2020-11-26 11:43 UTC
Labels: wontfix, workaround
